/**
 * @file uuid7.h
 * @brief Thread-safe binary UUIDv7 generation API.
 *
 * This module emits 16-byte UUIDv7 values using a 48-bit Unix millisecond timestamp, a monotonic 12-bit `rand_a` sequence, and a random
 * `rand_b` tail. The public API is intentionally binary-only: callers own formatting, storage, and transport encoding.
 *
 * Ordering contract:
 * - `uuid7_gen()` is safe to call concurrently from many threads.
 * - Within one process, generated `(timestamp, rand_a)` pairs are strictly increasing even if the wall clock stalls or moves backward.
 * - If a previous UUIDv7 is supplied to `uuid7_init()`, its `(timestamp, rand_a)` pair becomes a raise-only floor for future generation.
 * - The generator may advance its logical millisecond under extreme same-millisecond bursts after the 4096-entry `rand_a` space is
 * exhausted.
 *
 * Binary UUIDv7 layout used by this module:
 * @code
 * bytes 0..5  : unix_ts_ms, big-endian, 48 bits
 * byte  6     : high nibble = version 7, low nibble = rand_a[11:8]
 * byte  7     : rand_a[7:0]
 * byte  8     : high two bits = variant 0b10, low six bits = rand_b[61:56]
 * bytes 9..15 : rand_b[55:0]
 * @endcode
 *
 * @author  Roman Horshkov <https://github.com/RomanHorshkov>
 * @date    may 2026
 * (c) 2026
 */

#ifndef UUID7_H
#define UUID7_H

#include <stddef.h> /* size_t   */
#include <stdint.h> /* uint64_t */

#ifdef __cplusplus
extern "C"
{
#endif

/*****************************************************************************************************************************************
 * PUBLIC DEFINES
 *****************************************************************************************************************************************
 */

/**
 * @brief Size, in bytes, of a binary UUIDv7 value generated by this module.
 *
 * Callers must provide at least this many bytes to `uuid7_gen()`.
 */
#define UUID7_SIZE_BYTES 16u

/*****************************************************************************************************************************************
 * PUBLIC STRUCTURED VARIABLES
 *****************************************************************************************************************************************
 */
/* None */

/*****************************************************************************************************************************************
 * PUBLIC FUNCTIONS TYPEDEFS
 *****************************************************************************************************************************************
 */

/**
 * @brief Type of RNG function used to fill random bytes in UUIDs.
 *
 * The callback must attempt to fill exactly @p n bytes into @p buf and return a status code describing whether that operation succeeded.
 *
 * @param[out] buf  Output buffer to fill with random bytes.
 * @param[in]  n    Number of bytes to generate.
 *
 * @return 0 on success.
 * @return Negative value on failure.
 */
typedef int (*uuid7_rng_function_t)(void* buf, size_t n);

/*****************************************************************************************************************************************
 * PUBLIC FUNCTIONS DECLARATIONS
 *****************************************************************************************************************************************
 */

/**
 * @brief Initialize the UUIDv7 generator and optionally import persisted state.
 *
 * The RNG callback is installed first. If @p fn is NULL, the built-in default RNG is installed. If @p last_gen_uuid7 is not NULL, it must
 * point to a valid 16-byte UUIDv7 whose `(timestamp, rand_a)` pair is used as a monotonic floor. Import is raise-only: older persisted
 * UUIDs never rewind an already newer in-process state.
 *
 * Typical server usage is to call this once during startup, before worker threads begin generating IDs. Calling it later is still safe; the
 * RNG pointer and monotonic floor are updated atomically.
 *
 * @param[in] fn Optional RNG callback. Pass NULL to use the built-in system-entropy RNG.
 * @param[in] last_gen_uuid7 Optional previously generated UUIDv7 used to raise the monotonic floor.
 *
 * @return 0 on success.
 * @return -2 if @p last_gen_uuid7 does not encode UUID version 7.
 * @return -3 if @p last_gen_uuid7 does not encode the RFC variant bits.
 */
int uuid7_init(uuid7_rng_function_t fn, const void* last_gen_uuid7);

/**
 * @brief Raise the monotonic floor from a persisted UUIDv7 WITHOUT touching the
 *        RNG selection.
 *
 * For the common server pattern where the generator is initialized early (RNG)
 * but the newest existing id is only known later — e.g. after opening a database
 * and reading the maximum stored key. Importing it guarantees subsequently
 * generated ids sort AFTER everything already persisted, so time-ordered DBI
 * appends stay sequential across restarts, snapshot restores, and clock
 * rollbacks. Raise-only: an older floor never rewinds a newer in-process state.
 *
 * @param[in] last_uuid7 A valid 16-byte UUIDv7 (typically the max stored key).
 * @return 0 on success; -1 if NULL; -2/-3 if not a version-7 / RFC-variant UUID.
 */
int uuid7_raise_floor(const void* last_uuid7);

/**
 * @brief Number of clock_gettime() failures observed since process start.
 *
 * A failure still produces a unique id (random tail + monotonic sequence) but
 * with a zero timestamp, which is operationally misleading. Poll this as a
 * health metric and alert if it is ever non-zero. Thread-safe.
 *
 * @return Monotonically increasing failure count.
 */
uint64_t uuid7_clock_failure_count(void);

/**
 * @brief Generate one binary UUIDv7 value.
 *
 * Writes exactly UUID7_SIZE_BYTES bytes to @p out_buf. The function obtains the random tail before reserving the monotonic state, so RNG
 * failure does not consume a sequence value. On success, the reserved `(timestamp, rand_a)` pair is unique for the process and strictly
 * newer than the previous reservation.
 *
 * @param[out] out_buf Output buffer with at least UUID7_SIZE_BYTES writable bytes.
 *
 * @return 0 on success.
 * @return -1 if @p out_buf is NULL.
 * @return -2 if the active RNG cannot provide entropy.
 */
int uuid7_gen(void* out_buf);

/**
 * @brief Install the RNG callback used for UUID random-tail bytes.
 *
 * Passing NULL restores the built-in default RNG. The callback must fill exactly @p n bytes in @p buf and return 0 on success; any non-zero
 * return value makes `uuid7_gen()` fail with -2 before the monotonic state is advanced.
 *
 * The function is thread-safe and may race with `uuid7_gen()`. Each generation uses one atomically loaded callback pointer for the entire
 * random-tail fill.
 *
 * @param[in] fn RNG callback to install, or NULL to restore the default RNG.
 * @return 0 on success.
 */
int uuid7_set_rng_func(uuid7_rng_function_t fn);

#ifdef __cplusplus
}
#endif

#endif  // UUID7_H
