/**
 * @file uuid7.h
 * @brief Binary UUIDv7 generation interface with thread-safe monotonic ordering.
 *
 * UUIDv7 byte / bit layout
 *
 * 
 * Byte: 0...
 *  +----.----+----.----+ ...
 * | description |
 * Bits count 0:47
 * Bits length 12
 * 
 * @code
 * @brief Byte mapping:
 *
 *       0         1         2         3         4         5         6         7
 *  +----.----+----.----+----.----+----.----+----.----+----.----+----.----+----.----+
 *  |                         unix_ts_ms                        |ver |    rand_a    |
 *                               0:47                           48:51     52:63
 *                                6                               2         12
 *
 *       8         9         10        11        12        13        14        15
 *  +----.----+----.----+----.----+----.----+----.----+----.----+----.----+----.----+
 *  |var |                         rand_b                                           |
 *  64:65                             66:127
 *  2                                   62
 *
 *
 *  bytes 0..5  : unix_ts_ms, big-endian, 48 bits
 *  byte  6     : high nibble = version 7, low nibble = rand_a[11:8]
 *  byte  7     : rand_a[7:0]
 *  byte  8     : high two bits = variant 0b10, low six bits = rand_b[61:56]
 *  bytes 9..15 : rand_b[55:0]
 *
 * @endcode
 *
 * This internal 64-bit packed state is used only to guarantee monotonic,
 * non-decreasing `(timestamp, rand_a)` reservations across concurrent calls.
 * It is not the wire-format UUID by itself.
 *
 * @author  Roman Horshkov <https://github.com/RomanHorshkov>
 * @date    may 2026
 * (c) 2026
 */

#ifndef UUID7_H
#define UUID7_H

#include <stddef.h> /* size_t */
#include <stdint.h> /* uintX_t */

#ifdef __cplusplus
extern "C"
{
#endif

/****************************************************************************
 * PUBLIC DEFINES
 ****************************************************************************
 */

/**
 * @brief Size, in bytes, of a binary UUIDv7 value generated by this module.
 *
 * Callers must provide at least this many bytes to `uuid7_gen()`.
 */
#define UUID7_SIZE_BYTES 16u

/****************************************************************************
 * PUBLIC STRUCTURED VARIABLES
 ****************************************************************************
*/
/* None */

/****************************************************************************
 * PUBLIC FUNCTIONS TYPEDEFS
 ****************************************************************************
*/

/**
 * @brief Type of RNG function used to fill random bytes in UUIDs.
 *
 * The callback must attempt to fill exactly @p n bytes into @p buf and return
 * a status code describing whether that operation succeeded.
 *
 * @param[out] buf  Output buffer to fill with random bytes.
 * @param[in]  n    Number of bytes to generate.
 *
 * @return 0 on success.
 * @return Negative value on failure.
 */
typedef int (*uuid7_rng_function_t)(void* buf, size_t n);

/****************************************************************************
 * PUBLIC FUNCTIONS DECLARATIONS
 ****************************************************************************
*/

/**
 * @brief Explicitly initialize the UUID module and optionally configure the
 * RNG implementation.
 *
 * This function performs any module-local initialization that is required
 * before using `uuid7_gen()`. It also accepts an optional RNG function
 * pointer which will be used to generate cryptographically secure bytes.
 * If @p fn is NULL the module will install the built-in default RNG. Custom
 * RNG callbacks must return `0` on success and a negative value on failure.
 *
 * The function is idempotent and thread-safe. Typical usage: call
 * `uuid7_init(randombytes_buf)` after any global CSPRNG libraries (e.g.,
 * libsodium's `sodium_init()`) are initialized and before creating
 * application threads.
 *
 * @param[in] fn  Optional RNG function to use. NULL to install default.
 */
void uuid7_init(uuid7_rng_function_t fn);

/**
 * @brief Generate a UUIDv7 value.
 *
 * Produces a 16-byte RFC-v7 style UUID into the provided buffer.
 * The caller must supply a buffer of at least 16 bytes.
 * The function is safe to call concurrently from multiple threads,
 * uses an atomic CAS to reserve a monotonic (ms,seq) pair).
 * If more than 4095 UUIDs are generated within the same millisecond,
 * the generator advances the logical millisecond by 1 to preserve
 * monotonicity; this may embed a timestamp slightly ahead of wall
 * clock time under extreme burst rates.
 *
 * @param[out] val  Output buffer, must be at least 16 bytes.
 * @return 0 on success
 * @return -1 if @p val is NULL,
 * @return -2 if the active RNG reports failure or the built-in default
 *         RNG cannot provide entropy.
 */
int uuid7_gen(uint8_t* val);

/**
 * @brief Configure the RNG used by the UUID generator.
 *
 * If @p fn is non-NULL the UUID module will call this function to obtain
 * random bytes for sequence initialization and for the random tail.
 * If @p fn is NULL the module will reset to the built-in default RNG which
 * reads system entropy (getrandom(2) on Linux or /dev/urandom on fallback).
 * 
 * @note Custom RNG callbacks must return `0` on success and a negative value
 * on failure.
 *
 * Thread-safety: this function is thread-safe and may be called at any time.
 * The implementation guarantees safe concurrent reads/writes of the RNG
 * function pointer.
 *
 * @param[in] fn  RNG function pointer to use, or NULL to reset to default.
 */
void uuid7_set_rng_func(uuid7_rng_function_t fn);

#ifdef __cplusplus
}
#endif

#endif  // UUID7_H
